# Permalinks
#permalink:        pretty

# Theme
theme:            jekyll-theme-minimal

# Setup
title:            "Rakendustarkvara: R"
tagline:          Koolitus
url:              http://rkursus.github.io/
paginate:         1
baseurl:          /tykliinikum
author:
  name:           Kaur Lumiste
  url:            
  email:          kaur.lumiste@ut.ee

# Custom vars
version:          1.0.0
github:
  repo:           http://rkursus.github.io/tykliinikum

pages_list:       
  Koolituse materjalid: '/materjalid'
  Lisamaterjal: '/lisamaterjal'